---
title: "set up team permissions"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(googlesheets4)
library(googledrive)
library(synapser)

drive_auth(email = "pierrette.lo@sagebase.org")
gs4_auth(token = drive_token())
synLogin()
```

## get data from google sheet "Expansion & X01 data"

Don't forget to check the permission in the browser
If you forgot, use drive_auth() and choose 0 to get a new token
https://stackoverflow.com/a/68816877

```{r}
synapse_setup <- drive_get("https://docs.google.com/spreadsheets/d/1wNtmceBQwZu71gmQ1Z48yqNdV0zNu9WfZJ5IAhoRnMw/edit#gid=640167620") %>% 
  read_sheet("synapse_setup") %>% 
  filter(team_name != "INCLUDE_Admin" & 
           team_name != "INCLUDE_DMC")
```

Give cohort teams Download access to Data Curator App folder and Admin Fileview - NOT the Project

```{r}
#test with Cohort A
#DCA folder 
synSetPermissions("syn30109400", 3447914, c("READ", "DOWNLOAD"))

#Admin fileview
synSetPermissions("syn30109515", 3447914, c("READ", "DOWNLOAD"))

```

do this for all teams

```{r}
add_teams <- function(team_id){
  
  #DCA folder
  synSetPermissions("syn30109400", team_id, c("READ", "DOWNLOAD"))
  
  #Admin fileview
  synSetPermissions("syn30109515", team_id, c("READ", "DOWNLOAD"))
  
}

walk(.x = synapse_setup$team_id,
     .f = add_teams)

```

check that each cohort team has correct permissions for their own project

```{r}


perms <- map2(.x = synapse_setup$project_id,
     .y = synapse_setup$team_id,
     .f = synGetPermissions)
```

