---
title: "DS-DETERMINED Unharmonized Data Prep - DS-Connect"
---

```{r}
library(tidyverse)
library(synapser)
library(readxl)
library(janitor)

synLogin()

source(here::here("src/helpers/prep_unharmonized_data.R"))
```

# Read in data

```{r}
dsc_data <- read_csv(synGet("syn61348981")$path)
dsc_dict <- read_xlsx(synGet("syn61348983")$path)
```

# Check for duplicate Participant IDs

```{r}
dsc_data %>% get_dupes(col4) #0
```

# Get fields that are in data but not in dictionary
--> request from contributor

```{r}
setdiff(colnames(dsc_data), tolower(dsc_dict$`column name`)) %>% 
  str_c(collapse = ", ")
```

# Get fields that are in dict but not in data

```{r}
setdiff(tolower(dsc_dict$`column name`), colnames(dsc_data)) #0
```


# Get unique values from all columns
# Check for PHI
# compare enums/ranges to dictionary

- no PHI found
- did not check all the enums/ranges bc there are so many cols

```{r}
get_all_unique_values(dsc_data) %>%
  write_csv(here::here("output", "dsd_dsc_data_unique.csv"))
```


